spring.application.name=auth-service
server.port=8081
spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.datasource.url=jdbc:mysql://localhost:3306/auth_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
resilience4j.circuitbreaker.instances.userService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.userService.minimumNumberOfCalls=10
resilience4j.circuitbreaker.instances.userService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.userService.waitDurationInOpenState=60s
resilience4j.timelimiter.instances.userService.timeoutDuration=3s
